version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: toothbrush_app
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: toothbrush_db
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: toothbrush
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: